// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tbbciibejzpklxucafor.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRiYmNpaWJlanpwa2x4dWNhZm9yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIyMDE3NDgsImV4cCI6MjA3Nzc3Nzc0OH0.z3vuKEBPtyl6-muvBffGiY-z2-NQ0-Mm7nXzEbUYZiM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});